version: '2'
services:
  db:
    image: postgres:latest
    container_name: ps01
  nginx:
    container_name: ng01
    build:
      context: nginx
    ports:
      - "8000:8000"
    depends_on:
      - web
  web:
    build:
      context: prodjango
    container_name: dg01
    depends_on:
      - db
    expose:
      - "8000"
