version: '2'
services:
  nginx:
    container_name: ng01
    build:
      context: nginx
    ports:
      - "8000:8000"
  web:
    build:
      context: prodjango
    container_name: dg01
    expose:
      - "8000"
